name: LaTeX to PDF

on:
  push:
    branches:
      - master

  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: latex2pdf
        id: compile-latex-document
        uses: thomas-chauvet/latex2pdf-action@1.1.0
        with:
          output_dir: output
          main_latex_file: diss-docs/main_doc/main_doc.tex
          ctan_packages: geometry setspace caption subcaption graphix inputenc fontenc babel minted bookmark setspace fancyhdr lipsum
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output/main_doc.pdf
